// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BulkSelectorController from "./bulk_selector_controller"
application.register("bulk-selector", BulkSelectorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import PipelineSelectorController from "./pipeline_selector_controller"
application.register("pipeline-selector", PipelineSelectorController)

import ReactPortalController from "./react_portal_controller"
application.register("react-portal", ReactPortalController)

import ReadStatusController from "./read_status_controller"
application.register("read-status", ReadStatusController)

import TargetsSelectorController from "./targets_selector_controller"
application.register("targets-selector", TargetsSelectorController)
