FROM ruby:4.0.5-slim

RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libvips \
    git \
    curl \
    libyaml-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app


COPY Gemfile Gemfile.lock ./

RUN gem install bundler && bundle install

COPY . .

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"]