x-app: &app
  build:
    context: .
    dockerfile: Dockerfile.dev
  image: ruby:4.0.5-slim
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
  environment:
    - RAILS_ENV=development
    - REDIS_URL=redis://redis:6379/1
    - SEARXNG_URL=http://searxng:8080
  networks:
    - finder_network

services:
  tor:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: finder_tor
    networks:
      - finder_network

  db:
    image: postgres:18.4-alpine
    container_name: finder_db
    stdin_open: true
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - finder_network

  redis:
    image: redis:8.6.2-alpine
    container_name: finder_redis
    volumes:
      - redis_data:/data
    networks:
      - finder_network

  sidekiq:
    <<: *app
    command: bundle exec sidekiq -q scraping -q default
    networks:
      - finder_network
    depends_on:
      - db
      - redis

  searxng:
    build:
      context: ./searxng
      dockerfile: Dockerfile
    image: searxng/searxng:latest
    container_name: finder_searxng
    command: tor -f /etc/tor/torrc --Log "info stdout"
    volumes:
      - ./searxng:/etc/searxng
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_PROXIES_all=socks5h://tor:9050
    networks:
      - finder_network
    depends_on:
      - tor

  app:
    <<: *app
    container_name: finder_rails
    command: bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      searxng:
        condition: service_started

  tailwind:
    <<: *app
    command: bin/rails tailwindcss:watch

volumes:
  postgres_data:
  redis_data:

networks:
  finder_network:
    driver: bridge
