[botdetection]
ipv4_prefix = 32
ipv6_prefix = 48
trusted_proxies = []

[botdetection.ip_lists]
block_ip = []
pass_ip = [
  "127.0.0.1",
  "::1",
  "10.0.0.0/8",
  "172.16.0.0/12",
  "192.168.0.0/16"
]
pass_searxng_org = true

[botdetection.ip_limit]
filter_link_local = false
link_token = false
