
nightly_scraping_job:
  cron: "0 2,14 * * *"
  class: "NightlyScrapingCronJob"
  queue: "default"
  description: "Nightly scraping job"

searxng_updater_job:
  cron: "0 13 * * *"
  class: "SearxngUpdaterJob"
  queue: default